---
abstract: 'External libraries wrapped up for your viewing pleasure!'
author:
  - abergman@fotango.com
build_requires:
  Test::Pod: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien
provides:
  Alien:
    file: lib/Alien.pm
    version: '0.91'
resources:
  IRC: irc://irc.perl.org/#native
  MailingList: https://groups.google.com/forum/#!forum/perl5-alien
  license: http://dev.perl.org/licenses/
version: '0.91'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
